# Generated by Django 5.2.8 on 2025-11-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color_code',
            field=models.CharField(blank=True, default='', help_text='Optional hex color for this subject, e.g. #81E6D9', max_length=7),
        ),
    ]
