# Generated by Django 5.2.8 on 2025-11-30 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'ordering': ['school_class__name', 'period__day', 'period__order']},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_periods_per_day',
            field=models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
